Update capture
Signed-off-by: Ivan Valdes <ivan@vald.es>

diff --git a/.github/workflows/diff-lint.yaml b/.github/workflows/diff-lint.yaml
--- a/.github/workflows/diff-lint.yaml
+++ b/.github/workflows/diff-lint.yaml
@@ -29,7 +29,10 @@ jobs:
             disabled_rules="MD041"
           fi
           echo "::group::$file linter results"
-          echo "$diff" | awk 'match($0, /^(\033\[32m\+\033\[m\033\[32m|[^\033])(.*)\033\[m/, m){print m[2]}' | markdownlint -s --disable="$disabled_rules" || (has_failures=true && echo "::error::Linter exited with errors")
+          if ! echo "$diff" | awk '{ if (match($0, /^(\033\[32m\+\033\[m\033\[32m|[^\033])(.*)\033\[m$/, m)) { print m[2] } if (match($0, /^\033\[32m\+\033\[m$/)) { print "" } }' | markdownlint -s --disable "$disabled_rules"; then
+            has_failures=true
+            echo "::error::$file has linter issues"
+          fi
           echo "::endgroup::"
         done
         if [ "$has_failures" ]; then
